config/routes.rb
Rails.application.routes.draw do
	root to: 'todos#index'
	root 'todos#index'
	resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :todos
end

app/models/seed.rb
class Seed < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
	belongs_to :project, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@project = Project.all
	end
	def edit
		@todo = Todo.find(params[:id])
		if @todo.isCompleted == true
			@todo.update(isCompleted: false)
		else
			@todo.update(isCompleted: true)
		end
		redirect_to @todo
	end
	def create
		@project = Project.all
		@todo = Todo.new(todo_params)
		@todo.save
		redirect_to root_path
	end
	def show
		redirect_to root_path
	end
	private
		def todo_params
			params.require(:todo).permit(:text, :project_id)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def create
		@project = Project.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<html>
   <head>
      <title>!DOCTYPE</title>
      <meta charset="utf-8">
   </head>
   <body>
      <h1>Задачи</h1>
      <% titles = [] %>
      <% @project.each do |project| %>
      <h2><%= project.title %></h2>
      <%titles << [project.title.to_s, project.id]%>
      <ul>
         <% project.todos.each do |todo|%>
         <li><%= todo.text %></li>
         <% end %>
      </ul>
      <% end %>
      <input type = "button" value = "+" onclick="showHide('new_todo')">
      <div id = "new_todo" style="display: none;" >
         <h1>Новая задача</h1>
         <%= form_for :todo, url: todos_path, :html => {:id => "new_todo_form"} do |f| %>
         <p>
            <%= f.text_field :text %>
         </p>
         <p>
            <%= f.select(:project_id, titles) %>
         </p>
         <p>
            <a href="javascript:void(0)" onclick="showHide('new_todo')">ОТМЕНА</a>
            <a href="javascript:{}" onclick="document.getElementById('new_todo_form').submit(); return false;">OK</a>
         </p>
         <% end %>
      </div>
   </body>
</html>

app/views/todos/new.html.erb
hell

app/views/todos/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task})%>');﻿
m.modal('show');
$('#modal').integrateDatepicker();

app/views/welcome/index.html.erb
<h1>Задачи</h1>
<% titles = []
Project.all.each do |project| %>
	<h2><%= project.title %></h2>
	<% titles << project.title %>
	<ul>
		<% project.todos.each do |todo|%>
			<li><%= todo.text %></li>
		<% end %>
	</ul>
<% end %>

<h1>Новая задача</h1>

<%= form_for :project, url: projects_path do |f| %>
	<p>
		<%= f.label :text  %>
		<%= f.text_field :text %>
	</p>
	<p>
		<%= select(:project, :title, titles) %>
	</p>
	<p>
	<%= f.submit %>
	</p>
<% end %>